### ISSUE TITLE
About Graves AfterAttack Events broken?

### ISSUE THREAD

**Issue by N1ghtMoon** [LeagueSharp-Devs/LeagueSharp.SDKEx#11]
i try to write a graves assembly, but about Orbwalker.OnAction -> AfterAttack , not work with Graves ?

this is my problem or this is broken?

**Comment by ghost** [comment]
hi try using Obj_AI_Hero.OnProcessSpell or Obj_AI_Hero.OnDoCast (faster :klappa:) they should be able to detect his AA

**Comment by N1ghtMoon** [comment]
thanks, i will try it

**Comment by ghost** [comment]
PM me your graves assembly after you're done I really needed a good one :P

**Comment by N1ghtMoon** [comment]
i try to make it  better, but need L# support 6.10 path ,kappa

**Comment by ghost** [comment]
:feelssadman:

**Comment by ghost** [comment]
will look into it once L# is updated
btw whats ur forum name :eyebrows:

**Comment by N1ghtMoon** [comment]
NightMoon

**Comment by N1ghtMoon** [comment]
today i test again, AfterAttack also not work
